# Generated by Django 4.2.7 on 2023-12-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0002_playlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("recorded_at", models.DateField()),
                ("length_in_seconds", models.IntegerField()),
            ],
        ),
    ]
