# Generated by Django 4.2.7 on 2023-12-03 16:38

from django.db import migrations, models
import playlists.validators


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0003_music"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="length_in_seconds",
            field=models.IntegerField(
                validators=[playlists.validators.validate_music_length]
            ),
        ),
    ]
