version: '3'
# 1 - Utilize a imagem wordpress:php8.0 e mysql:5.7.40;
services:
  db:
    image: mysql:5.7.40
# 5 - Defina o volume db_data para o mysql;
    volumes:
      - db_data:/var/lib/mysql
# 7 - Adicione a política de restart com o valor always aos serviços;
    restart: always
# 4 - Defina as seguintes variáveis para o mysql:
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
# 6 - Utilize o parâmetro depends_on para criar dependência entre os serviços;
    depends_on:
      - db
    image:  wordpress:php8.0
# 2 - Faça bind da porta 80 do container do wordpress para 8080 do host
    ports:
      - "8080:80"
# 7 - Adicione a política de restart com o valor always aos serviços;
    restart: always
# 3 - Defina as seguintes variáveis para o wordpress:
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data: {}

# 8 - Suba os serviços utilizando docker-compose e abra no terminal para validar o funcionamento.s
    