# Cria um Dockerfile utilizando a imagem chuanwen/cowsay
FROM chuanwen/cowsay:latest
# Define um ENTRYPOINT para a execução do comando
ENTRYPOINT [ "/usr/games/cowsay/" ]
# Utiliza o CMD para definir uma mensagem padrã
CMD [ "#VQV Trybe" ]
