# version: '3'

# services:
#   mysql_container:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: playlist-manager-mysql-container
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: playlist_manager_database

