version: '3'

services:
  app:
    container_name: app_associations
    image: node:18-alpine
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    container_name: db_associations
    image: mysql:5.7
    restart: always
    env_file:
      - .db_env
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
