version: '3'

services:
  app:
    image: node:18-alpine
    container_name: books_app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    container_name: books_database
    image: mysql:5.7
    restart: always
    env_file:
      - .db_env
    ports:
      - 33060:3306
